In [41]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

# ==========================================
# Crear el DataFrame original
# ==========================================

data = {
    "ID": [1, 2, 3, 4],
    "Edad": [25, 45, 30, 40],
    "Ciudad": ["Madrid", "Sevilla", "Madrid", "Barcelona"],
    "Ingresos": [30000, 50000, np.nan, 40000]
}

df = pd.DataFrame(data)

print("DataFrame original:")
df.head()

DataFrame original:

   ID  Edad     Ciudad  Ingresos
0   1    25     Madrid   30000.0
1   2    45    Sevilla   50000.0
2   3    30     Madrid       NaN
3   4    40  Barcelona   40000.0

In [42]:
# ==========================================
# Imputar valor faltante (media)
# ==========================================

imputer = SimpleImputer(strategy="mean")
df["Ingresos"] = imputer.fit_transform(df[["Ingresos"]])

print("\n Dataframe después de imputar valor faltante:")
df.head()

 Dataframe después de imputar valor faltante:

   ID  Edad     Ciudad  Ingresos
0   1    25     Madrid   30000.0
1   2    45    Sevilla   50000.0
2   3    30     Madrid   40000.0
3   4    40  Barcelona   40000.0

In [43]:
# ==========================================
#  Label Encoding
# ==========================================
df_encoded = df.copy()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df_encoded["Ciudad_Label"] = le.fit_transform(df_encoded["Ciudad"])
print("\n Después de aplicar Label Encoding:")
df_encoded.head()

 Después de aplicar Label Encoding:

   ID  Edad     Ciudad  Ingresos  Ciudad_Label
0   1    25     Madrid   30000.0             1
1   2    45    Sevilla   50000.0             2
2   3    30     Madrid   40000.0             1
3   4    40  Barcelona   40000.0             0

In [44]:
# ==========================================
#  One-Hot Encoding (Scikit-Learn)
# ==========================================

ohe = OneHotEncoder(sparse_output=False)

ciudad_encoded = ohe.fit_transform(df[["Ciudad"]])

ciudad_ohe_df = pd.DataFrame(
    ciudad_encoded,
    columns=ohe.get_feature_names_out(["Ciudad"])
)

df_ohe = pd.concat([df, ciudad_ohe_df], axis=1)

print("\n Después de One-Hot Encoding:")
df_ohe.head()

 Después de One-Hot Encoding:

,ID,Edad,Ciudad,Ingresos,Ciudad_Barcelona,Ciudad_Madrid,Ciudad_Sevilla
0,1,25,Madrid,30000.0,0.0,1.0,0.0
1,2,45,Sevilla,50000.0,0.0,0.0,1.0
2,3,30,Madrid,40000.0,0.0,1.0,0.0
3,4,40,Barcelona,40000.0,1.0,0.0,0.0

In [45]:
# ==========================================
#  Variables Dummy (Pandas)
# ==========================================

df_dummies = pd.get_dummies(df, columns=["Ciudad"], drop_first=False)

print("\n Variables Dummy:")
df_dummies.head()

 Variables Dummy:

   ID  Edad  Ingresos  Ciudad_Barcelona  Ciudad_Madrid  Ciudad_Sevilla
0   1    25   30000.0             False           True           False
1   2    45   50000.0             False          False            True
2   3    30   40000.0             False           True           False
3   4    40   40000.0              True          False           False

In [46]:
# ==========================================
#  Escalamiento
# ==========================================

#  Min-Max Normalization
scaler_minmax = MinMaxScaler()
df[["Edad_MinMax", "Ingresos_MinMax"]] = scaler_minmax.fit_transform(
    df_dummies[["Edad", "Ingresos"]]
)

#  Z-Score Standardization
scaler_std = StandardScaler()
df_dummies[["Edad_Z", "Ingresos_Z"]] = scaler_std.fit_transform(
    df_dummies[["Edad", "Ingresos"]]
)

print("\n Dataframe con dummies y después del escalamiento:")
df_dummies.head()

 Dataframe con dummies y después del escalamiento:

,ID,Edad,Ingresos,Ciudad_Barcelona,Ciudad_Madrid,Ciudad_Sevilla,Edad_Z,Ingresos_Z
0,1,25,30000.0,False,True,False,-1.264911,-1.414214
1,2,45,50000.0,False,False,True,1.264911,1.414214
2,3,30,40000.0,False,True,False,-0.632456,0.000000
3,4,40,40000.0,True,False,False,0.632456,0.000000

In [47]:
# ==========================================
#  Guardar dataset final
# ==========================================

df_dummies.to_csv("dataset_preprocesado.csv", index=False)

print("\n Dataset guardado como dataset_preprocesado.csv")

 Dataset guardado como dataset_preprocesado.csv